### ISSUE TITLE
Consulta security code

### ISSUE THREAD

**Issue by yamifr07** [mercadopago/sdk-ios#10]
Hola, en mi app simplemente necesito crear un token a partir de los datos de la tarjeta, ya que el payment lo creo desde el server. Para ello, estoy llamando a startPaymentMethodsViewController, startNewCardViewController y por ultimo a createNewCardToken.
El problema es que al new card view controller le paso que requiere un security code pero no me lo solicita (las variables requireSecurityCode y securityCodeCell no se usan) y no quiero programar mi propia ui de security code.

Se puede incorporar a la sdk?

**Comment by matiasgualino** [comment]
Hola @yamifr07 esto que decís lo estamos haciendo en el Ejemplo 1 de nuestra SDK. 

Descarga el repositorio, ábrelo con el Xcode y prueba la aplicación de ejemplos. Luego puedes usar ese mismo código para crear tu formulario y hacerle las adaptaciones que necesites. 

Alternativa 1) puedes arrancar un Vault, sin especificar la URI para customer y allí también usar nuestra UI con la solicitud de cuotas e inclusive el pedido del código de seguridad.
Alternativa 2) Usar nuestra Row de SecurityCode (también disponible en el código).

Saludos
