### ISSUE TITLE
Xcode 7 "swift usage" code doesn't work

### ISSUE THREAD

**Issue by manisolutions14** [mercadopago/sdk-ios#6]
I am tried to develop project using Mercadopago cocoapods podfile and tried to run project using below code but doesn't show any update. Please reply..... :(

==========================================================================
Swift:
        import MercadoPagoSDK
        func initMercadoPagoVault() {
                let supportedPaymentTypes = ["credit_card", "debit_card", "prepaid_card", "ticket", "atm"]

        let vaultViewController = MercadoPago.startVaultViewController("444a9ef5-8a6b-429f-abdf-587639155d88",
            merchantBaseUrl: "https://www.mercadopago.com", 
            merchantGetCustomerUri: "/checkout/examples/getCustomer", 
            merchantAccessToken: "mla-cards-data", 
            amount: 10.0, 
            supportedPaymentTypes: supportedPaymentTypes) { 
            (paymentMethod, tokenId, issuerId, installments) -> Void in
                            let alert = UIAlertController()
                            alert.title = "Payment Info"

                            var msg = "Token = \(token?._id!). \n Payment method = \(paymentMethod.name!). \n"
                            msg = msg + " Installments = \(installments!)."
                            msg = msg + " CardIssuer ID = \(cardIssuerId != nil ? cardIssuerId! : cardIssuerId)"

                            alert.message = msg
                            alert.addAction(UIAlertAction(title: "Finish", style: .Default, handler: { action in
                            switch action.style{
                                case .Default:
                                    self.nav!.popToRootViewControllerAnimated(true)
                                    self.nav!.popViewControllerAnimated(true)
                                    self.initViewController()
                                case .Cancel:
                                    println("cancel")
                                case .Destructive:
                                    println("destructive")
                            }
                            }))
                            self.nav!.presentViewController(alert, animated: true, completion: nil)
                        }
                // Put vaultController at the top of navigator.
                self.nav!.pushViewController(vaultViewController, animated: false)
        }
==========================================================================

**Comment by matiasgualino** [comment]
Hi, if you're using XCode 7 and Swift 2, I think that the following code helps you:

Podfile
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
pod 'MercadoPagoSDK', '~> 0.3.0'

Delete podfile.lock, Pods and Build folders. In your terminal run "pod install".
Don't use XCode Beta, because the Latest SDK is 9.1 and we not support yet.

AppDelegate.swift

import UIKit
import CoreData
import MercadoPagoSDK

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
	var window: UIWindow?
	var nav: UINavigationController?
	
	func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
		// Initialize window
		self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
		self.window?.backgroundColor = UIColor.whiteColor()
		self.nav = UINavigationController()
		
		let vaultViewController = MercadoPago.startVaultViewController(
			"444a9ef5-8a6b-429f-abdf-587639155d88",
			merchantBaseUrl: "https://www.mercadopago.com",
			merchantGetCustomerUri: "/checkout/examples/getCustomer",
			merchantAccessToken: "mla-cards-data",
			amount: 100.50,
			supportedPaymentTypes: ["credit_card", "debit_card", "prepaid_card", "ticket", "atm"]) {
				(paymentMethod, tokenId, issuerId, installments) -> Void in
				let alert = UIAlertView(title: "Payment Info", message: "Token = \(tokenId!). \n\nPayment method = \(paymentMethod.toJsonString()). \n\nInstallments = \(installments). \n\nIssuerId = \(issuerId != nil ? issuerId! : issuerId)", delegate: nil, cancelButtonTitle: "Cancel")
				alert.show()
		}
		self.nav!.pushViewController(vaultViewController, animated: false)
		
		self.window?.rootViewController = self.nav	
		self.window?.makeKeyAndVisible()
		return true
	}
}

Regards,

Matias.

**Comment by rakesh-ideal** [comment]
We are tried to use Mercadopago but it’s only working for iOS < 10.0 coding language swift < 3.0 Coding Tool Xcode < 8.0

But we had developed app on iOS 8.0 to above with coding language swift  3.3.0 & Coding Tool Xcode 8.3.2.There are available  Mercadopago SDK for swift 3.3.0 but it’s not working.
